### ISSUE TITLE
Molisa Moyo Coding Interview (Technical assessment)

### ISSUE THREAD

**Issue by tangani** [teraflow-ai/data-engineer-coding-interview#10]
Created all resources using Terraform and managed to populate the database using a separate script which is included in the pull request

**Comment by PsycheShaman** [comment]
@tangani I think perhaps you forgot to raise the pull request?

**Comment by tangani** [comment]
Hi Christiaan,

Apologies for this.

This is Molisa's repo and for some reason I forgot to mention that my
GitHub profile is under my second name and should have alerted you soon
after making the pull request on Friday.

Thank you for taking note of this.

Best regards,
Molisa S. T. Moyo

**Comment by PsycheShaman** [comment]
Hi Molisa

All good, however, this is not a pull request, it is a Github issue.

Kind regards
CG Viljoen, MSc
<https://www.credly.com/badges/8fb9d197-c3c5-43da-b9b2-07102867f0e0/public_url>[image:
AWS Certified Data Analytics – Specialty]
<https://www.credly.com/badges/2edd02ba-f0f3-4194-934c-9d2500662dd5/linked_in?t=rhs81j>[image:
How to Pass the GCP ACE Exam: Part 1]
<https://www.credential.net/617b2bfa-1bba-4f6d-9c89-c6a23d8eb58a?key=3b3986e3f5e571c783ae48ed41574692f9ca97c58d7ba62ee7a5ec102d1d5bcd>[image:
Get Certified: Google Cloud Certified Professional – Data Engineer | SAP
Blogs] <https://www.credential.net/55337d57-39cc-4e84-98b5-ab68837e06b3>
